version: '3'
services:
  mysql:
    image: shomaigu/mysql-database-class
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    volumes:
    - ./mysql:/var/lib/mysql

    environment:
    - MYSQL_ROOT_PASSWORD=root
    - TZ=Asia/Tokyo
    ports:
    - "3306:3306"
    restart: always

  flask:
    container_name: db_flask
    build:
      context: ./flask
      dockerfile: Dockerfile
    volumes:
    - ./flask/requirements.txt:/usr/src/app/requirements.txt
    - ./flask/app.py:/usr/src/app/app.py
    - ./flask/templates:/usr/src/app/templates
    - ./flask/static:/usr/src/app/static
    ports:
      - 80:80
    restart: always
    tty: true
